PIAFS:
  ports:
  - 10080:80/tcp
  tty: true
  image: pierredalpe/docker_piafs
  links:
  - DB:mysql
  stdin_open: true
  volumes_from:
  - PIAFS-data
  environment:
    DB_NAME: piafs-db-name
    DB_PASS: piafs-db-pass
    DB_HOST: mysql
    DB_USER: piafs-db-user

PIAFS-data:
  command:
  - /bin/true
  tty: true
  image: pierredalpe/docker_piafs
  links:
  - DB:mysql
  stdin_open: true
  volumes:
  - ../PIAfS/backups:/backups


DB:
  environment:
    MYSQL_DATABASE: piafs-db-name
    MYSQL_PASSWORD: piafs-db-pass
    MYSQL_ROOT_PASSWORD: piafs-root-pass
    MYSQL_USER: piafs-db-user
  domainname: piafs-mysql
  tty: true
  image: mariadb:10.0
  stdin_open: true
  volumes_from:
  - DB-data

DB-data:
  command:
  - /bin/true
  tty: true
  image: mariadb:10.0
  volumes:
  - ../PIAfS/mysql:/var/lib/mysql
  stdin_open: true
